# Generated by Django 5.2.5 on 2025-09-05 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_newslettersubscriber_alter_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='created_at',
        ),
    ]
